### ISSUE TITLE
Images don't come with Flask installed

### ISSUE THREAD

**Issue by jeancochrane** [azavea/docker-flask#5]
It seems like these images don't have Flask installed out of the box. Not sure if this is an intentional choice, but I figured I might open an issue to check anyway.

Looking at #4, I can tell that the old version of the Dockerfile installed Flask:

https://github.com/azavea/docker-flask/blob/40872769ee7e9fd40baea6ac8ea2fe4a909af2c6/Dockerfile#L12-L15

Then #4 split the Dockerfile into alpine/jessie versions and moved dependencies to requirements files:

https://github.com/azavea/docker-flask/blob/e1ee919df4f04d3d31cc1a74b5444829a3bcd5ba/Dockerfile-alpine.template#L11

https://github.com/azavea/docker-flask/blob/e1ee919df4f04d3d31cc1a74b5444829a3bcd5ba/Dockerfile-slim.template#L13

Neither of the requirements files have Flask installed, however:

https://github.com/azavea/docker-flask/blob/e1ee919df4f04d3d31cc1a74b5444829a3bcd5ba/0.12/requirements.txt#L1-L2

https://github.com/azavea/docker-flask/blob/e1ee919df4f04d3d31cc1a74b5444829a3bcd5ba/0.11/requirements.txt#L1-L2

### Steps to reproduce

Set up the following `docker.compose.yml`:

```yml
version: '3'

services:
  test-flask:
    image: quay.io/azavea/flask:0.12-python2.7-alpine
    entrypoint: pip freeze
```

Run `docker-compose run test-flask` to confirm that Flask isn't installed:

```
$ docker-compose run test-flask
appdirs==1.4.2
gevent==1.2.1
greenlet==0.4.12
gunicorn==19.6.0
packaging==16.8
pyparsing==2.1.10
six==1.10.0
```

**Comment by tnation14** [comment]
@jeancochrane wow, thanks for the catch! I'll get on this right away.
